class APIResponse<T> {
  T? data, data1;
  String? Status,
      status,
      Message,
      message,
      http_status,
      status_message,
      token,
      assessment_form;
  num? total_questions,
      responses,
      pictures,
      completed_assessments,
      pending_assessments,
      total_assessments,
      total_pictures,
      total_bed,
      given_bed,
      total_staff,
      given_staff;

  APIResponse(
      {this.data,
      this.data1,
      this.Status,
      this.status,
      this.Message,
      this.message,
      this.status_message,
      this.token,
      this.http_status,
      this.total_questions,
      this.responses,
      this.pictures,
      this.total_assessments,
      this.completed_assessments,
      this.pending_assessments,
      this.assessment_form,
      this.given_bed,
      this.given_staff,
      this.total_bed,
      this.total_staff,
      this.total_pictures});

  Map<String, dynamic> toMap() {
    return {
      'data': data,
      'data1': data1,
      'Status': Status,
      'status': status,
      'Message': Message,
      'message': message,
      'status_message': status_message,
      'token': token,
      'http_status': http_status,
      'total_questions': total_questions,
      'responses': responses,
      'pictures': pictures,
      'total_assessments': total_assessments,
      'completed_assessments': completed_assessments,
      'pending_assessments': pending_assessments,
      'assessment_form': assessment_form,
      'given_bed': given_bed,
      'given_staff': given_staff,
      'total_bed': total_bed,
      'total_staff': total_staff,
      'total_pictures': total_pictures,
    };
  }

  factory APIResponse.fromMap(Map<String, dynamic> map) {
    return APIResponse(
      data: map['data'] as T,
      data1: map['data1'] as T,
      Status: map['Status'] ?? '',
      status: map['status'] ?? '',
      Message: map['Message'] ?? '',
      message: map['message'] ?? '',
      http_status: map['status'] ?? '',
      status_message: map['status_message'] ?? '',
      token: map['token'] ?? '',
      total_questions: map['total_questions'],
      responses: map['responses'],
      pictures: map['pictures'],
      total_assessments: map['total_assessments'] ?? 0.0,
      completed_assessments: map['completed_assessments'] ?? 0.0,
      pending_assessments: map['pending_assessments'] ?? 0.0,
      assessment_form: map['assessment_form'] ?? '',
      given_bed: map['given_bed'] ?? 0.0,
      given_staff: map['given_staff'] ?? 0.0,
      total_bed: map['total_bed'] ?? 0.0,
      total_staff: map['total_staff'] ?? 0.0,
      total_pictures: map['total_pictures'] ?? 0.0,
    );
  }
}
